version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Create a network and connect the app container to it
    networks:
      - devcontainer-network

  mongodb:
    image: mongo:8
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      # Connect using mongodb://root:example@mongodb:27017/

    # Add "forwardPorts": ["mongodb:27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    networks:
      - devcontainer-network

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
      ME_CONFIG_BASICAUTH: false

    # Add "forwardPorts": ["mongo-express:8081"] to **devcontainer.json** to forward Mongo-express locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    networks:
      - devcontainer-network

  activemq:
    image: apache/activemq-artemis:2.37.0-alpine
    restart: unless-stopped
    volumes:
      - artemis-data:/var/lib/artemis-instance
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis

    # Add "forwardPorts": ["activemq:8161"] to **devcontainer.json** to forward ActiveMQ Artemis locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    networks:
      - devcontainer-network

networks:
  devcontainer-network:

volumes:
  mongodb-data:
  artemis-data:
